db.employees.find()
db.employees.find().skip(1)
db.employees.find().limit(1)
db.employees.find().skip(1).limit(1)
db.employees.find({department:"IT"})
db.employees.find({department:"IT"},{_id:0,name:1})
db.employees.find({department:"IT"},{_id:0,name:1,salary:1})
